.github/workflows/changelogger.yml

fix(action): Action only run on created

---

app/authentication/exceptions.py
app/authentication/views.py
app/content/exceptions.py
app/content/models/event.py
app/content/models/registration.py
app/content/serializers/user.py
app/content/views/cheatsheet.py
app/content/views/event.py
app/content/views/job_post.py
app/content/views/news.py
app/content/views/page.py
app/content/views/registration.py
app/group/views/membership.py

Removed the Django translation functions, denoted by underscores before a string or message returned from the API, since all messages returned are to be written in norwegian.
Issue number: closes #20 

refactor(django): remove django translation string functions

---

CHANGELOG.md
app/content/serializers/event.py

fix(event): create event with priorities

---

app/fixture.json

Updated fixtures with relevant data
View the data here: https://kvark.vercel.app/, https://lepton-api.herokuapp.com/api/admin/

refactor(fixtures): update fixtures

---

app/fixture.json

fix(fixtures): removed forms because of causes unnecessary problems

---

app/content/serializers/event.py
app/tests/content/test_event_integration.py

refactored events integration test to be writen like the other tests
Issue number: closes #6 

refactor(events): refactored events integration test

---

app/content/admin/admin.py

Added search fields in registration admin so that you can search on a username og event title to find a match registration
Issue number: closes #17
None

feat(Admin): Added search fields in registration admin

---

app/content/views/strike.py

fix(strike): update queryset

---

app/content/signals.py
requirements.txt

fix(celery): revert version to 4.4

---

.github/workflows/deploy_dev.yml
Dockerfile
docker-compose.dev.yml

fix(docker): copy files in docker build

---

.github/workflows/deploy_prod.yml
CHANGELOG.md
docker-compose.prod.yml

-  Creates automatic deployment to production of Azure on push to master

feat(azure): add production azure config

---

app/content/factories/user_factory.py
app/group/management/commands/migrate_members.py
app/tests/groups/test_migrate_members_command.py

Add management command to migrate all TIHLDE members to our TIHLDE group.
The command can be run with `docker-compose run --rm web python manage.py migrate_members`
Issue number: No issue

feat(groups): add command to migrate tihlde members to tihlde group

---

app/content/filters/user.py

fix(user): activate user

---

CHANGELOG.md
app/content/templates/activated_member.html
app/content/views/makeTIHLDEMember.py
app/group/views/membership.py

- Sends email when a user is activated
- Creates notification when a user is added to a group
- Creates notification when a user is made leader in a group
Issue number: closes #123 closes #122 

feat(notifications): mail on made member

---

app/content/models/user.py
app/content/views/user.py

fix(user-perm): fixed update permissions

---

.github/workflows/ci.yaml
.github/workflows/deploy_dev.yml
.github/workflows/deploy_prod.yml

Correct wrong path for Azure deploy scripts due to #101 
Issue number: 

fix(cd): update path to dockerfile for deploy scripts

---

CHANGELOG.md
app/content/views/user.py

Endret til alltid returnere UserMemberSerializer ved update av user
Issue number: closes #152 

fix(user): update own user as admin

---

app/content/templates/passwordResetEmail.html
app/static/templates/base.html
app/static/templates/mail_creator.html

Fix issue with formatting in emails, break for new-lines, wider on desktop and white links.

refactor(mail): format html better

---

CHANGELOG.md
app/forms/serializers/__init__.py
app/forms/serializers/forms.py
app/forms/serializers/statistics.py
app/forms/serializers/submission.py
app/forms/urls.py
app/forms/views/statistics.py
app/forms/views/submission.py
app/group/models/membership.py

Added endpoint to get statistics of answers to forms. Also in this PR i added pageination and user to the submissions. 
Under you can find the output from the two endpoints
Issue number: closes #182 
```json
//output from /forms/<forms_id>/submission
{
"count": 2,
"next": null,
"previous": null,
"results": [
{
"answers": [
{
"id": "6edbf0e8-666e-4e81-984d-fcf6dd13aba8",
"field": {
"id": "1330dfc6-4437-48e5-a67e-9a7c4f916cf1"
},
"selected_options": [],
"answer_text": "hello"
},
{
"id": "a0238092-8ea3-4278-b6e2-00cc45a2db14",
"field": {
"id": "32f909c9-ec61-4762-a92f-550d76a40a50"
},
"selected_options": [
{
"id": "6d78f41e-ac75-461d-8a34-19a6cf7b8415",
"title": "lolo"
}
],
"answer_text": ""
},
{
"id": "af5e01d6-3069-4a34-979a-33d9c83f64e9",
"field": {
"id": …
```

feat(statistics): added endpoint to get statistics of answers to forms

---

app/forms/serializers/statistics.py

feat(statistics): percentage on forms submissions

---

app/content/models/registration.py
app/content/tests/test_registration_model.py

https://github.com/TIHLDE/Lepton/issues/177
Issue number: closes #177 

feat: remove submission upon deregistrations

---

app/content/models/registration.py
app/content/tests/test_registration_model.py
app/forms/models/forms.py
app/forms/views/form.py

fix(registration): added check for answered form

---

app/content/filters/event.py
app/content/views/event.py

Issue number: closes #210
- [] CHANGELOG.md has been updated. [Guide](https://tihlde.slab.com/posts/changelog-z8hybjom)

refactor(event): changed default queryset filtering

---

CHANGELOG.md
app/forms/csv_writer.py
app/forms/views/submission.py
requirements.txt

Tillater admins å generere .csv fil med alle svar på skjemaer.
Issue number: closes #187 

feat(submissions): submission csv download

---

CHANGELOG.md
app/content/tasks/event.py

fix(strike): bug where registrations on wait would get strikes

---

app/content/models/registration.py
app/content/tests/test_registration_model.py
app/content/views/registration.py

fix(registration): fixed bug where an automatic bump would increase the event limit

---

CHANGELOG.md
app/forms/models/forms.py
app/forms/views/submission.py

fix(forms): csv filter on form id and users not on wait

---

CHANGELOG.md
app/forms/models/forms.py
app/forms/views/submission.py
app/tests/forms/test_submission_integration.py

feat(submissions): overwrite submission if it does not have an event

---

app/content/views/user.py

* fix(strikes): get user strike
* Update user.py

Fix strikes

---

app/forms/models/forms.py

Permissions-sjekken i `GroupForm.has_write_permission()` ble kjørt av en eller annen grunn da man skulle hente ut innlogget bruker. Endret så denne ikke kan heve en feil.
Issue number: No issue

fix(forms): fix 500 error in group for list permission for /me

---

app/tests/content/test_user_integration.py

The actions on th euser viewset does not have tests, so if they fail because of changes we wont't know, this PR adds simple tests to check if they are working and not retruning somthing likke a 500 error

feat(user-tests): added test to check if user view action are working correctly

---

app/group/serializers/fine.py
app/group/views/fine.py

feat(fines): added statistics for fines

---

app/forms/models/forms.py

Fikser issue som hindrer oppdatering av EventForm hvis man ikke sender inn event sammen med oppdatert data.

fix(forms): eventform permissions

---

Makefile

Gjort MAKEFILE ryddigere ved å bruke .PHONY for å få en bedre kommando oversikt ved `make` eller `make help`
God Jul @TIHLDE/index 🎄

chore(make): improve makefile

---

docker-compose.dev.yml
docker-compose.prod.yml

Inneholder oppdaterte docker-compose filer for Azure

chore(cloud): update docker-compose files

---

app/content/views/strike.py

fix(strike): fixed buged that created a 500 error on creation

---

.gitignore
app/content/views/event.py

fix(event): fixed expired filtering

---

app/content/admin/admin.py

Issue number: closes #18 
- [ x ] Pull request title follows [conventional commits](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) (`type(scope): description`)
- [ x ] Format and lint (`make format` and `make flake8`) was run locally without failures

feat(registration): added field created_at and updated_at in admin panel

---

app/common/tasks.py

fix(log): fixed wrong filter field when trying to delete old logs

---

app/common/permissions.py

Ganske sikker på at dette fikser Sentry feil

fix(permissions): check if user exists

---

app/gallery/filters/album.py
app/gallery/views/album.py

feat(gallery): added search and event filtering to albums

---

app/content/filters/event.py

fix(events): wrong name in method name on event filter

---

app/content/filters/event.py
app/content/views/event.py

fix(events): queryset filtering

---

app/communication/events.py
app/content/views/event.py

added back the default event filter 

fix(events): fixed filtering on events

---

CHANGELOG.md
app/content/views/event.py
app/tests/content/test_event_integration.py

Fikset issue der admins fikk 404 ved uthenting av et enkelt event. 

fix(events): 404 error for admin retrival

---

app/content/views/event.py
app/tests/content/test_event_integration.py

Filtrering skjedde ikke for admins men skal nå fungere igjen  

fix(events): include filtering for admins

---

CHANGELOG.md
app/gallery/views/picture.py

Håndterer nå alt av opplastning slik at frontend kun må sende inn filene som skal inn i albumet.

refactor(gallery): upload flow

---

app/forms/models/forms.py

fix(forms): email on submission (#492)

---

app/content/models/user.py
app/content/serializers/user.py
app/tests/content/test_user_integration.py
requirements.txt

La til mulighet for å sende med gruppeslug ved brukeropprettelse for å legge til brukeren i grupper for studier og trinn. Disse trenger ikke bli sendt med så vi kan ha brukere som ikke tilhører studier/trinn.
Issue number: closes #483 

refactor(user): class and study groups for user registration

---

app/content/factories/__init__.py
app/content/models/registration.py
app/content/tests/test_registration_model.py

feat(registration): fixed bug where strikes were enforced on events that has it turned off

---

app/forms/models/forms.py

Tillater frontend å ikke sende med group i request når et spørreskjema skal endres

fix(group-form): allow write when group not in data

---

app/badge/admin.py
app/badge/filters/badge.py
app/content/admin/admin.py
app/content/filters/strike.py
app/content/filters/user.py
app/content/models/user.py
app/content/serializers/event.py
app/content/serializers/user.py
app/content/views/strike.py
app/content/views/user.py
app/fixture.json
app/group/models/group.py
app/group/serializers/__init__.py
app/group/serializers/membership.py

Forbereder backend på fjerning av user_class og user_study. Fjerner bruken av dem alle steder som ikke er relatert til prioriteringer. Disse siste stedene det brukes fjernes i ny pr når priority_pools er klart i ny pr

refactor: user class and study

---

app/badge/admin.py
app/badge/filters/badge.py
app/content/admin/admin.py
app/content/filters/strike.py
app/content/filters/user.py
app/content/models/event.py
app/content/models/user.py
app/content/serializers/event.py
app/content/serializers/user.py
app/content/views/event.py
app/content/views/strike.py
app/content/views/user.py
app/fixture.json
app/group/models/group.py
app/group/serializers/__init__.py
app/group/serializers/membership.py

Må legge personer til i grupper for study og studyyear før ny oppdatering av master der user_class og user_study forsvinner

Friday update 🍟 

---

CHANGELOG.md
app/content/models/event.py
app/group/serializers/__init__.py
app/group/serializers/group.py
app/group/views/group.py

feat: added enpoint for group statistics

---

app/content/serializers/__init__.py
app/content/serializers/news.py
app/content/views/news.py

refactor: change news list endpoint to return less info

---

app/constants.py

Endret e-post.
Issue number: closes #604 
Not needed for this small pr 

ref(epost): Endret e-post

---

CHANGELOG.md
app/content/models/registration.py
app/content/models/strike.py
app/content/views/user.py
app/group/views/membership.py

Fikset noen kommafeil :)
Issue number: closes #628

chore(grammar): Added very important commas.

---

CHANGELOG.md
app/content/models/registration.py
app/content/tasks/event.py

Fikset noen flere grammatiske "feil" :nerd_face: 
Issue number: closes #630 

chore(grammar): Even more grammar fixes :nerd_face:

---

README.md

READMEen er nå mer konsis og lettere å lese.
Issue number: closes #632

chore(readme): Improved readme! :wrench:

---

setup.cfg

I have fixed flake8
Issue number: closes #671

Fixed flake8

---

app/common/enums.py
app/content/models/event.py
app/tests/conftest.py
app/tests/content/test_event_integration.py

Jubkom needs permissions fast to create events

Added Event permissions to Jubkom temporarily

---

CHANGELOG.md
app/common/enums.py
app/content/models/news.py
app/tests/content/test_news_integration.py

Added fondet to allowed list of news

Added Fondet to allowed and fixed typo

---

app/settings.py

Removed TASK_ALWAYS_EAGER from TRUE when run in local.

removed celery task_always_eager local variable

---

app/content/serializers/event.py

Vi bør legge til om arrangementet er betalt eller ikke. Dette gjør logikken i frontend mye bedre

fix: added is_paid_event

---

app/group/admin.py

Added search bar for admin page for memberships. You can now search for first- and lastname for users. This makes it easier to find the users that need change of study or studyyear.

added search bar for admin site for memberships

---

app/content/models/registration.py

Users on the wait list will now get notifications when bumped up from waiting list.

notification for waiting list and when coming from waiting list

---

app/settings.py

I nytt infrastrukturoppsett må vi kunne kontrolere URLen til Celery brokeren

use env variable for celery broker url

---

CHANGELOG.md
app/content/models/user.py
app/tests/content/test_user_integration.py

Give HS user permissions

---

app/content/models/event.py
app/content/models/registration.py
app/content/serializers/event.py
app/settings.py
app/tests/conftest.py
app/tests/content/test_event_integration.py

If an events limit is increased, members from  the waitlist is bumped up.
If an events limit is decreased, members from the queue is bumped down.
Priority is respected.

Fix(registration)/waitlist limit

---

app/common/enums.py

There are issues for member of KoK to create news, events and manually adding registrations. Now members of kok can do that by adding the slug kontkom (PK) to the access

Update AdminGroup enum value KOK to Kontkom

---

app/content/views/user.py

fixed event filter

---

app/content/models/event.py
app/tests/content/test_event_integration.py

Remove write permission for members of Jubkom on Event

removed write permission on Event for jubkom

---

app/content/serializers/user.py
app/payment/models/order.py
app/payment/views/order.py
app/tests/payment/test_order_integration.py

Refactor the permission logic to the order model and removed it from the viewset

added permission checks for order model and removed from order viewset

---

app/payment/models/order.py

fixed string representation for orders

fixed string representation for orders

---

app/content/admin/admin.py
app/content/factories/__init__.py
app/content/factories/logentry_factory.py
app/content/serializers/content_type.py
app/content/serializers/logentry.py
app/content/urls.py
app/content/views/__init__.py
app/content/views/logentry.py
app/tests/content/test_logentry_integration.py

Added viewset and serializer for Django built in LogEntry model:
Also removed date_hierachy from admin  register for LogEntry since our new DB is not configured for timezone.

LogEntry viewset and fix

---

app/kontres/serializer/reservation_seralizer.py
app/kontres/views/reservation.py
app/tests/kontres/test_reservation_integration.py

when reservation response is made, it will include the full objects of the author, group and bookable item

Feat(kontres)/return full objects in response

---

app/content/models/registration.py
app/tests/content/test_event_integration.py

Fix(event)/fix priority waiting number

---

app/content/views/user.py
app/kontres/views/reservation.py
app/tests/kontres/test_reservation_integration.py

added endpoint for a user to fetch all his reservations

Feat(kontres)/add endpoint for my reservations

---

app/kontres/views/bookable_item.py
app/kontres/views/reservation.py
app/tests/kontres/test_bookable_item_integration.py
app/tests/kontres/test_reservation_integration.py

custom delete messages when deleting objects

Fix(kontres)/custom delete message

---

app/content/models/registration.py
app/content/util/registration_utils.py

fixed paymenttime saved to db

---

CHANGELOG.md
app/content/serializers/category.py
app/content/serializers/event.py

This PR adds a serializer for category in event category

Added serializer for category in  event

---

app/content/models/qr_code.py
app/content/views/qr_code.py

This will add permission methods to the QR code model

Permission refactor of QR Codes

---

infrastructure/database.tf
infrastructure/storage.tf

* Adding destroy prevention on our data storage resources

feat(iac): add terraform guardrails so index don't nuke our infra

---

.gitignore
.terraform.lock.hcl
infrastructure/containers.tf
infrastructure/inputs.tf
main.tf

Feide env variables Terraform

---

app/forms/csv_writer.py

updated csv for forms

---

app/content/models/news.py
app/content/models/user.py
app/forms/models/forms.py
app/tests/content/test_news_integration.py
app/tests/forms/test_group_form_integration.py

Permission for group forms and news

---

.github/workflows/ci.yaml
CHANGELOG.md
app/content/serializers/event.py
compose/Dockerfile

GitHub Action to check if Swagger is up

Swagger GitHub Action

---

Makefile
scripts/app.py

add a script for setting up a new app in Lepton and creating all needed directories and files

Add new app

---

scripts/app.py

Added serializers dir to app init

App Script Fix

---

CHANGELOG.md
app/content/serializers/registration.py
app/payment/serializers/order.py

Added a field to the serializer of registrations for an event to include payment history.

Event registration payment orders

---

scripts/app.py

Added admin.py to root in new app, and added app dir to tests

---

app/career/views/weekly_business.py
app/content/views/upload.py

Fix information leak issue explained in #913.

Fix issue where full error is exposed to external users

---

app/gallery/filters/album.py

You can now sort galleries by date in both orders and after event titles. 
Issue number: closes #897 

Sort galleries

---

app/payment/models/order.py

added write_all auth to order model

---

CHANGELOG.md
app/forms/csv_writer.py
app/payment/models/order.py

fixed csv download bugs

---

app/apikey/views/email.py

allow no buttons key
