TIHLDE/Lepton

- .github/workflows/pull_request_actions.yaml
- Pipfile.lock
Updated pull_request_actions to use the previous version of ubuntu (v18) where mysql starts automatically. Also updated github secrets to match the service config.
> fix(ci): make pull_request_actions.yaml (test and lint) run again

- CHANGELOG.md
- app/career/serializers/weekly_business.py
- app/career/views/weekly_business.py
- app/common/serializers.py
- app/content/admin/admin.py
- app/content/serializers/badge.py
- app/content/serializers/category.py
- app/content/serializers/cheatsheet.py
- app/content/serializers/event.py
- app/content/serializers/job_post.py
- app/content/serializers/news.py
- app/content/serializers/notification.py
- app/content/serializers/page.py
- app/content/serializers/priority.py
- app/content/serializers/registration.py
- app/content/serializers/short_link.py
- app/content/serializers/user.py
- app/content/serializers/user_badge.py
- app/content/views/cheatsheet.py
- app/content/views/event.py
- app/content/views/notification.py
- app/content/views/page.py
- app/content/views/short_link.py
- app/fixture.json
- app/forms/serializers/forms.py
- app/forms/serializers/submission.py
- app/group/serializers/group.py
- app/group/serializers/membership.py
- app/group/views/group.py
Implement automatic logging of actions taken on models either through the API or django admin. The former currently only supports logging upon creation/update. Implemented using Django's built-in LogEntry model. 
These log entries are immutable to preserve an accurate log history.
Issue number: closes #37 
The logging via api usage happens in LoggerSerializer, but I chose to inherit from a BaseModelSerializer instead in case we need to alter inheritance in the future.
> feat(logging): django admin and api-wide logging of model actions 

- .github/workflows/deploy_dev.yml
There's an issue in Azure where the App Service configuration is changed on CI/CD push and I suspect that's because we manually push the image to the webapp. Therefore this removes the push through Github Actions and we instead use the "Countinuous deployment"-setting in App Service Deployment configuration which automatically updates when a new image is pushed to the selected container registry.
> fix(azure): don't deploy to webapp through action

- Dockerfile
- docker-compose.yml
- requirements.txt
Much faster Docker builds.
Use python3.6-slim-buster base image in Dockerfile to speed up build and avoid pitfalls described [here](https://pythonspeed.com/articles/alpine-docker-python/) which includes slower build times for python, potentially obscure bugs, larger images and more work. 
Issue number: No issue
With Alpine Linux you need to compile all the C code in every Python package that you use which is one of the reasons it is slower.
> refactor(docker): use python-slim-buster and clean up dockerfile + compose

- docker-compose.yml
Docker-compose was not able to pick up code changes due to a mismatch in the volumes mounts. This fix reverts the volumes mapping back to what we previously had.
Issue number: No issue
> fix(docker): change docker-compose volumes mapping to match Dockerfile

- app/group/models/group.py
- app/group/serializers/group.py
- app/settings.py
Added a field on group serializer to see if a user has permissions to change that group or not
> feat(group-permissions): added field on group serializer to see if a user has permissions

- app/content/views/event.py
The endpoints where resulting in 500 Internal Server Error when an invalid id was passed to the uri /events/<pk>
Issue number: closes #69 
> fix(event): change usage of django orm for event retreival to using drf's self.get_object to handle invalid inputs

- CHANGELOG.md
- app/content/views/registration.py
- app/tests/content/test_registration_integration.py
Allows users to set allow_photo to false onregistration to event. Added test
Issue number: closes #114 
> fix(registrations): users can set allow-photo to false

- CHANGELOG.md
- app/settings.py
Update domain setting to `api.tihlde.org` in order to fix issue where the reset-password link would take the user to the old api-domain. 
Issue number: closes #118 
> fix(reset-password): update reset password domain to api.tihlde.org

- CHANGELOG.md
- app/authentication/views.py
- app/content/filters/user.py
- app/content/models/user.py
- app/content/serializers/__init__.py
- app/content/serializers/user.py
- app/content/views/user.py
- app/fixture.json
- First removed the `is_TIHLDE_member` property in a try to increase speed/performance, but without luck
- The solution seems to be removing permissions from the serializer. I therefore created a new UserListSerializer without "permissions".
- Removed "app_token", "events", "badges", "groups", "unread_notifications" and "home_busstop" fields as well, couse I can't see why an admin user should need to see that info. Can discuss wether more fields also should be removed from the serializer.
- PR in Kvark will be created as well to support these changes
Issue number: closes #102 
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you …
> refactor(user): improve speed on list request

- docker-compose.dev.yml
- docker-compose.prod.yml
- docker-compose.yml
Turns off heartbeats, mingle and gossip messages from celery to our RabbitMQ hosted at CloudAMQP. Config has been updated in Azure. We should wait merging this until we have confirmed that the updated config fixes the issue. Shouldn't take more than a day to check.
Issue number: closes #110 
> fix(celery): disable rabbitmq heartbeats

- CHANGELOG.md
- app/authentication/serializers/__init__.py
- app/authentication/serializers/make_user.py
- app/authentication/urls.py
- app/authentication/views.py
- app/content/views/makeTIHLDEMember.py
- app/group/serializers/membership.py
The problem was that `@permission_classes([IsDev, IsHS])` checks if the user fullfills both `IsDev` *and* `IsHS`. As Index members also get permission through `IsHS`, we didn't notice this. Switching to `(IsHS|IsDev,)` fixes this as it's an logial OR-check instead of logical AND.
Also removed an excessive `makeMember`-function at the unused `/auth/make`-endpoint.
Also changed user-serializer in membership-serializer to a more performat version.
> fix(permissions): let hs activate new users

- CHANGELOG.md
- app/content/serializers/user.py
HS and Index didn't have acces to edit users. Updated with giving them access to everything on the user except user_id
> fix(users): allow admin to update user-data

- CHANGELOG.md
- app/content/serializers/__init__.py
- app/content/serializers/page.py
- app/content/views/page.py
Added serach and pagination to the response when searching, this search only allows you to search on all pages, and cannot restrict the search to a spesific folder. its used by adding the query param serach page/?search=lover
Issue number: closes #39 
> feat(pages): added serach and pagination to the response when searching

- CHANGELOG.md
- app/content/signals.py
- app/content/tasks/event.py
- docker-compose.yml
- requirements.txt
Quite sure that it works, but not 100% sure
- Upgraded Celery to new major version 5.0.5
- Fixed revoke issue (I think)
- Changed how the event is retrieved by using the celery "request.id" instead
- This means that only 1 event can have that id, and therefore other tasks will not find the event and therefore not run
- This also allows us to not add kwargs to the task
- This should be manually tested, steps:
1. Add flower-image as new container
- This allows you to see all tasks and info about them
2. Adjust eta in apply_async to run soon after save so you don't have to wait
3. Turn of setting which makes this only run in production
Issue number: closes #31 
If this is a relatively large or complex change, kick off the …
> fix(celery): fix revoke and prevent duplicate runs

- CHANGELOG.md
- app/content/signals.py
- app/content/tasks/event.py
- requirements.txt
- Oppdatert `celery` versjon til 5.1.2 uten at det inkluderer noen store endringer.
- Endret også oppdatering av events i `signals.py` til å bruke `queryset.update()` istedenfor `event.save()` siden save() fører til ny kjøring av signalet og dermed legger opp til en evig rekursjon som er problemet i #160 .
- La til `*args, **kwargs` som parametre i celery-tasks'ene for å fjerne errors som har oppstått.
Issue number: closes #160 
> fix(celery): stop stack overflow on event save

- CHANGELOG.md
- app/group/models/membership.py
- app/group/tests/test_membership_model.py
Added logic for promoting and swaping hs members when a leader of a subgroup is changed.
Issue number: closes #105 
> feat(membership): added functionality for swapping hs members

- app/content/views/user_badge.py
- app/forms/serializers/statistics.py
- app/forms/views/form.py
- app/forms/views/submission.py
- app/tests/forms/test_form_integration.py
Fixes bug which lead to a divide by zero error, a wrong response code on destroy and an error where all submissions was returned on `/submission/`, with no filtering of form
> fix(forms): statistics and submissions

- CHANGELOG.md
- app/util/utils.py
Switch to using Djangos Built-in Template to format datetime which also automatically formats dates with both localization and timezone
Issue number: closes #175 
> fix(timezone): fix timezone formatting for emails

- CHANGELOG.md
- app/content/exceptions.py
- app/content/factories/__init__.py
- app/content/factories/event_factory.py
- app/content/mixins.py
- app/content/models/registration.py
- app/content/models/user.py
- app/content/serializers/event.py
- app/content/tests/test_user_model.py
- app/settings.py
- app/tests/conftest.py
- app/tests/content/test_registration_integration.py
~**Avventer svar på om det skal gjelde for både NoK og Sosialen sine arrangementer**~
Ikke tillat brukere med ubesvarte evalueringer å melde seg på arrangementer hvis de har et ubesvart evalueringsskjema. Dette styres av en bryter man kan styre med en miljøvariabel. Den er av frem til TIHLDE/Kvark#161 er utført.
Lagt til et felt når man henter ut ett event som angir om brukeren har det øvrige.
Issue number: closes #185 
> feat(registration): deny registrations for users with unanswered evaluations

- CHANGELOG.md
- app/forms/serializers/forms.py
- app/tests/forms/test_form_integration.py
New field: `viewer_has_answered`
Issue number: closes #212 
> feat(forms): add viewer has answered to form

- app/content/models/user.py
- app/content/serializers/event.py
- app/content/serializers/registration.py
- app/content/serializers/user.py
La til feltet `unanswered_evaluations_count` på `UserSerializer`, flyttet `viewer_has_unanswered_evaluation` til `RegistrationSerializer` og endret til at den gjelder kun for akkurat det arrangementet. Endret navn på siste til `has_unanswered_evaluation`.
Issue number: Ingen issue
> refactor(submissions): move unanswered evaluation fields for users and registrations

- CHANGELOG.md
- app/common/mixins.py
- app/content/models/user.py
- app/content/views/user.py
- app/tests/content/test_user_integration.py
- app/util/utils.py
La til endepunktet `/users/me/forms/` hvor en bruker kan hente ut forms den har svart på, med filtrering på om det er ubesvart. Filtreringen vil bare filtrere ubesvarte evalueringer, siden dette er det eneste som kan tolkes som ubesvart og som fortsatt kan knyttes til en bruker.
La også til en `ActionMixin` som reduserer duplikat kode i `@action` metoder som kun returnerer paginert data.
Slettet også `app/forms/serializers/form.py` da denne var utdatert og ubrukt. 
Issue number: closes #201 
> feat(user): include own submissions in /me/forms

- app/content/models/user.py
- app/content/serializers/user.py
Fix issues with PR that went through QA a bit fast 😉 
- `has_unanswered_evaluations_for` now returns a boolean and not an array
- `get_unanswered_evaluations_count` now actually returns a number
Issue number: no issue
> fix(forms): unanswered_evaluations typos

- app/content/models/registration.py
- app/settings.py
- app/tests/content/test_registration_integration.py
Fjernet bryteren som styrer begrensninger i påmeldinger for brukere med med ubesvarte evalueringsskjemaer, da denne funksjonaliteten skal være inkludert overalt.
Issue number: Ingen issue
> refactor(registration): remove evaluation switches

- CHANGELOG.md
- app/forms/models/forms.py
- app/tests/forms/test_form_integration.py
Members of NoK didn't have access to view submissions, this gives them access. We should probably create a better system for access handling in forms based on formtype and recourcetype
Issue number: closes issue mentioned in Slack
> fix(forms): allow nok to view submissions

- CHANGELOG.md
- app/content/models/registration.py
- app/content/tests/test_registration_model.py
Gjennom #292 kom det inn en bug som hindrer admins i å markere brukere som ankommet på et arrangement hvis det  er noen på arrangementets venteliste. Grunnen til det var at det ble sjekket om arrangementet hadde en venteliste, om det var fullt og om "Registration" som blir lagret `not is_on_wait`, isåfall ble det kastet en exception. Problemet her var at påmeldinger som allerede hadde plass og dermed ikke økte antall påmeldinger med plass også fikk denne exception ved save.
Har løst dette ved å gjøre `save` atomic, save registration og så sjekke om antall med plass er høyere enn limit. Hvis så kastes exeception og save av registration rulles tilbake.
If this is a relatively large or complex change, kick …
> hotfix(registration): set attended when event has queue

- app/content/views/user.py
Fixes a bug where you couldn't load a user's strikes if any of the strikes where connected to an event which had an `organizer != None`. The bug came because the request wasn't passed as context to the serializer which needed it to add group permissions in response
> fix(strikes): get user strike

- CHANGELOG.md
- app/group/factories/group_factory.py
- app/group/models/fine.py
- app/group/models/group.py
- app/group/serializers/fine.py
- app/group/tests/test_group_model.py
- app/group/views/membership.py
Added notifications when creating a fine, and if a user is promoted to fines admin they are sendt an email with information about their new role
Issue number: closes #364 
> feat(fines): fines now sends out notifs and fine admins now gets an email

- .github/ISSUE_TEMPLATE/bug.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
- .github/ISSUE_TEMPLATE/refactor_suggestion.yml
- .github/scripts/changelogger.py
- .github/workflows/changelogger.yml
- .github/workflows/deploy_dev.yml
- .github/workflows/deploy_prod.yml
- .github/workflows/deploy_to_azure.yml
- CHANGELOG.md
- Makes use of the reusable workflows for continuous deployment
- Add issue templates
- Change versioning style. Now uses the format `Versjon YYYY.MM.dd`, eks: `Versjon 2021.05.23`
- This is beacuse a semantic version doesn't make sense when we don't publish or make our api publicly available.
> chore(github): reuse workflows, issue templates and changelog versioning

- CHANGELOG.md
- app/communication/notifier.py
- app/content/models/registration.py
- app/content/models/strike.py
- app/content/views/user.py
- app/forms/serializers/__init__.py
- app/forms/serializers/submission.py
- app/group/serializers/__init__.py
- app/tests/content/test_user_integration.py
- app/util/export_user_data.py
Brukere kan få tilsendt egne brukerdata på epost ved å sende en GET-request til `users/me/data/`. Dataen kommer som en zip-fil med en json-fil per modell der bruker-relasjon finnes.
Issue number: closes #397 
> feat(gdpr): user data export

- CHANGELOG.md
- app/forms/serializers/__init__.py
- app/forms/serializers/forms.py
- app/forms/views/form.py
- app/tests/forms/test_form_integration.py
Merged together FormSerializer and AnswerableFormSerializer as the only difference between these two is the field `viewer_has_answered`. In addition, I added the field `resource_type` to  FormSerializer. With this, listing all form templates will display `resource_type `and `viewer_has_answered`. This is needed for TIHLDE/Kvark#323.
Issue number: closes #403 
> fix(forms): added resource_type and viewer_has_answered to formserializer

- CHANGELOG.md
- app/content/models/user.py
- app/content/views/accept_form.py
- app/static/templates/base.html
Fikser en feil som førte til at alle brukere fikk `users: { write: true }` i permissions selv om de kun kunne endre egen bruker. Nå får kun Index og HS-medlemmer `write: true`. Fikset også en liten bug i accept-form og oppdatert url til index i mails.
> fix(users): permission write check

- CHANGELOG.md
- app/common/azure_file_handler.py
- app/common/file_handler.py
- app/common/serializers.py
- app/content/views/user.py
- app/gallery/views/album.py
- app/gallery/views/picture.py
- Fikset feil som oppstod ved opplastning av profilbilde.
- Her var det 2 forskjellige typer feil:
- Hvis eksisterende bilde hadde space i url, så var det ikke mulig å finne bildet i Azure uten å urldecode
- Hvis eksisterende instans var null i databasen, så ga `settings.AZURE_BLOB_STORAGE_NAME in instance.image` feilen i #435 
- Håndterer input av ugyldig badge samt forsøk på å få samme badge flere ganger
- Sender en respons ved sletting av galleri og bilder i galleri.
Issue number: closes #486 closes #435 
> fix(exceptions): image and badge exceptions

- .envs/.local
- CHANGELOG.md
- README.md
- app/settings.py
- docker-compose.dev.yml
- docker-compose.prod.yml
- docker-compose.yml
Issue number: closes #477 
Kjører RabbitMQ i Docker-Compose istedenfor å ha en egen instans i Azure Container Instances ettersom ingen viktig data lagres der.
> refactor(rabbitmq): run in docker-compose

- CHANGELOG.md
- app/communication/models/user_notification_setting.py
Added an extra check to make sure the Slack account is connected if it is to be used as the only notification channel.
You may not disable the two other channels if Slack is not connected.
Issue number: closes #538 
> fix(notification): Avoid Slack as only channel when not connected

- requirements.txt
Downgrading Django version from 4.1 to 4.0. Det er kjente problemer mellom django og rest-framework med django 4.1. Det er foreslått å nedgradere til 4.0 for å fikse problemet. https://github.com/encode/django-rest-framework/pull/8591
Feilen de refererer til er akkurat samme feil som vi får i dev-miljøet. 
Denne fiksen skal fikse dev-miljøet 🤞 
> fix(django): django and django-rest-frameworks issues

- CHANGELOG.md
- app/content/models/user.py
- app/tests/conftest.py
- app/tests/content/test_user_integration.py
HS have decided that HS members no longer can change or delete users. Changed their permissions.
Issue number: closes #651 
> HS can't change users

- app/group/admin.py
- compose/Dockerfile
- docker-compose.yml
- requirements.txt
> Updating Database Release

- app/communication/serializers/banner.py
- app/communication/views/banner.py
Banner filtering var broken og vi bør ikke sortere på custom modell properies. Prøvde å finne eksempler, men det er anbefalt å bare sortere på vanlige modell properties
> fix: filtering and improve serilizer

- CHANGELOG.md
- app/content/exceptions.py
- app/content/models/registration.py
- app/content/models/user.py
- app/content/serializers/event.py
- app/content/views/registration.py
- app/settings.py
- app/tests/content/test_user_integration.py
- app/tests/payment/test_paid_event_integration.py
Not allow to remove paid event from event
> Remove option to update from paid event to free event

- CHANGELOG.md
- app/content/models/registration.py
- app/content/serializers/registration.py
- app/content/tests/test_registration_model.py
Added a wait_queue_number field on the RegistrationSerializer so that users can see which place they have in the waitlist.
Issue number: closes #721
I chose the solution of finding the count of users in the waitlist that were added before you, in other words, performing an aggregation query for each request. I did this instead of adding a field on the Registration model itself, since that would mean mutating every waitlist registration of the event whenever one person is moved up the queue.
> Feat(event)/waitlist

- app/kontres/serializer/reservation_seralizer.py
- app/tests/kontres/test_reservation_integration.py
was a bug where the time validation was called when doing a put request, which compared the starttime to Now() which is a check that should only be run on reservation creating. 
> fixed logic in serializer method for validating time

- app/content/models/registration.py
When an user get upped from the waiting list, the payment_counter that checks if the order is paid, does not start. I have fixed this bug now.
> fixed bug of payment countdown for registrations from waitlist to queue

- app/kontres/serializer/reservation_seralizer.py
- app/tests/kontres/test_reservation_integration.py
full sober watch user object will now be returned in response. can be accesses via sober_watch_detail from frontend
> Fix(kontres)/return full sober watch

- app/content/filters/user.py
> added filter for allowed photos for user

- app/common/permissions.py
Per now, a request can check the token in the DB 2-5 times for one single request. Added a check that prevent duplicate DB calls.
> Permission middelware

- app/common/permissions.py
- app/content/serializers/user.py
- app/content/views/user.py
- app/payment/models/order.py
- app/payment/views/order.py
- app/tests/payment/test_order_integration.py
This will fix permissions for payment orders
> Permissions for payment orders

- .github/workflows/ci.yaml
- app/common/file_handler.py
- app/content/serializers/user.py
- app/content/urls.py
- app/content/util/feide_utils.py
- app/content/views/__init__.py
- app/content/views/feide.py
- app/content/views/upload.py
> added delete endpoint for file

- app/content/urls.py
- app/files/urls.py
Move urls for creation and deletion of files back to the content url for backwards compatability.
> Move file upload and deletion to content from files

- app/forms/models/forms.py
- app/forms/serializers/submission.py
- app/forms/views/submission.py
Added deletion of a submission including a reason for the deletion. In the serializer I made a SubmissionDestroySerializer that validates the reason for deleting a submission and ensure that it's not empty. In view I made a destroy_with_reason method that allows an administrator to delete a submission and send an email to the user notifying them about the deletion and why it's deleted. The reason for the deleted submission will be passed via the request data and used in the email notification.
Issue number: closes #830 
> Feat(submissions)/deletion of form submission

- app/settings.py
Tydeligvis så klarer man ikke å konfigurere miljøet som lepton kjører i riktig. Så jeg sier fuck det nå sender vi alt til __BARE__ https://tihlde.org dersom man tester lokalt, da får man bare bytte ut den linken selv synd for den personen. Denne bugen har vært her lenge og nå sier jeg meg ferdig med den...
Takk for meg.
> FIX(Email links): Fjerner auto-detect environment.
